#!/bin/bash
python3 -c $'import os\nw="water"\ns="stir"\nb="bestchol"\nW=os.environ["WATER"]\nS=os.environ["STIR"]\nd1=sum(w.index(c)*5**i for i,c in enumerate(reversed(W)))\nd2=sum(s.index(c)*4**i for i,c in enumerate(reversed(S)))\nn=d1+d2\nr=""\nexec("while n>0:\\n r=b[n%8]+r\\n n=n//8")\nprint(r)'
