#!/bin/bash
echo $(awk 'BEGIN{w="water";s="stir";b="bestchol";W=ENVIRON["WATER"];S=ENVIRON["STIR"];d1=0;for(i=1;i<=length(W);i++){c=substr(W,i,1);for(j=1;j<=5;j++)if(substr(w,j,1)==c)d1=d1*5+(j-1)};d2=0;for(i=1;i<=length(S);i++){c=substr(S,i,1);for(j=1;j<=4;j++)if(substr(s,j,1)==c)d2=d2*4+(j-1)};n=d1+d2;r="";while(n>0){r=substr(b,n%8+1,1)r;n=int(n/8)};print r}')
